version: '3.3'

networks:
  purchase_network:
    driver: bridge
    ipam:
      config:
        - subnet: 145.0.0.0/16


services:
  purchase-app:
    image: purchaseappapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      purchase_network:
        ipv4_address: 145.0.0.3
    depends_on:
      - purchase_postgres
  purchase_postgres:
    container_name: purchase_postgres
    image: postgres:13.5
    ports:
      - "5432:5432"
    networks:
      purchase_network:
        ipv4_address: 145.0.0.2
    environment:
      POSTGRES_USER: "PURCHASE_ACCOUNTING_ADMIN"
      POSTGRES_PASSWORD: "PURCHASE_ACCOUNTING_LOCAL"
