springdoc:
  api-docs:
    enabled: true

logging:
  level:
    root: "INFO"

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: PURCHASE_ACCOUNTING_ADMIN
    password: PURCHASE_ACCOUNTING_LOCAL
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    open-in-view: false
  database:
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true #Enable false for production
    url: jdbc:postgresql://localhost:5432/postgres
    schemas: public
    user: "PURCHASE_ACCOUNTING_ADMIN"
    password: "PURCHASE_ACCOUNTING_LOCAL"

server:
  port: 8082
  max-http-form-post-size: 100MB

